INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (1, 'Consultas médicas', 'Atención médica para diagnóstico y tratamiento.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (2, 'Servicio de urgencias', 'Atención médica inmediata para emergencias.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (3, 'Laboratorio clínico', 'Pruebas de laboratorio para diagnóstico y seguimiento.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (4, 'Servicio de radiología', 'Imágenes médicas para diagnóstico.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (5, 'Tomografía computarizada (TC)', 'Imágenes transversales detalladas del cuerpo.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (6, 'Resonancia magnética (RM)', 'Imágenes detalladas con imanes y ondas de radio.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (7, 'Mamografía', 'Radiografía de los senos para detectar cáncer de mama.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (8, 'Ecografía', 'Imágenes en tiempo real mediante ondas sonoras.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (9, 'Pruebas de embarazo', 'Detección de la hormona hCG para confirmar embarazo.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (10, 'Electrocardiograma (ECG)', 'Registro de actividad eléctrica del corazón.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (11, 'Vacunación', 'Administración de vacunas para la prevención de enfermedades infecciosas.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (12, 'Servicio de fisioterapia', 'Terapia física para rehabilitación y recuperación de lesiones y trastornos musculoesqueléticos.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (13, 'Servicio de rehabilitación', 'Programas y terapias para recuperación funcional después de lesiones o cirugías.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (14, 'Servicio de nutrición y dietética', 'Asesoramiento y planificación de dietas saludables para promover una buena nutrición y prevenir enfermedades.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (15, 'Servicio de psicología', 'Evaluación y tratamiento de problemas de salud mental y emocional.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (16, 'Servicio de farmacia', 'Dispensación de medicamentos y asesoramiento farmacéutico.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (17, 'Servicio de atención prenatal', 'Cuidado médico especializado durante el embarazo, incluyendo seguimiento prenatal y pruebas de rutina.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (18, 'Planificación familiar', 'Asesoramiento y métodos anticonceptivos para control de la fertilidad y planificación de embarazos.');
INSERT INTO emergenciasguide.servicio (idServicio, nombre, detalle) VALUES (19, 'Terapia ocupacional', 'Terapia para mejorar la independencia y la capacidad funcional en actividades diarias.');
